feat:[RP-31] - added features product card with two variants: ProductCard and ProductCardMain
frontend-education-projects/rozetka pull request #10
Opened 2023-02-14 14:23 UTC by dipSyxx

# Title
Product card

## Ticket Link
https://rozetka-home-project.atlassian.net/browse/RP-31

## Changes
-Added features product card: ProductCard and ProductCardMain
-Added data api with info about product card

## Info

## Screenshots
UI:
![Screenshot_2](https://user-images.githubusercontent.com/113060461/218765684-963a9a4f-057f-4dbb-a3f6-2572cef26fc6.png)

2023-02-22 00:08 UTC, MaksPapirovnyk commented on src/features/ProductCard/components/ProductImage/index.tsx
> +        ref.current.addEventListener('mouseover', handleMouseOver)
Make sure that you also remove event listeners

2023-02-22 00:10 UTC, MaksPapirovnyk commented on src/features/ProductCard/components/ProductImage/index.tsx
> +        ref.current.addEventListener('mouseover', handleMouseOver)
why not useEffect?

2023-02-22 00:13 UTC, MaksPapirovnyk commented on src/features/ProductCardMain/components/ProductImageMain/index.tsx
> +        <img alt="Product" src={imageUrl} />
I see that you often disable the Next Image rule, why? The next Image is very useful for product cart images

2023-02-22 00:15 UTC, MaksPapirovnyk commented on src/features/ProductCardMain/index.tsx
> +import { ProductCardMainInfoProps } from '@data/ProductCardInfo'
I think will be more semantic to store component type in the component, and if you need to import this type into a data file.

2023-02-22 00:17 UTC, MaksPapirovnyk commented on src/pages/index.tsx
> +              {productsCards}
Why? Why not just render it here? :)

2023-02-22 00:18 UTC, MaksPapirovnyk commented on src/pages/index.tsx
> +        id: number
It’s weird to make typing inside the map, maybe will be better to have a product card type globally?

2023-02-22 00:19 UTC, MaksPapirovnyk commented on src/pages/index.tsx
> +        id: number
simply use `ProductCardMainInfo?.map`

2023-02-22 00:23 UTC, MaksPapirovnyk commented on src/pages/index.tsx
> +        id: number
basically, if your data was already typed, in your case you set type for the `ProductCardMainInfo` in the data folder.
so you can just map it.
considering that this is currently mocked data, and in the future, it will be replaced with real data from an API request, you will also have a chance to type data.

2023-02-22 00:25 UTC, MaksPapirovnyk requested changes
1. take a look at your css, try extract variables
2. don't hesitate with eslint rules
3. reafactor types storing, make it more consistent and reusable
4. the rest looks good, good job!

2023-02-22 15:11 UTC, dipSyxx commented on src/features/ProductCard/components/ProductImage/index.tsx
> +        ref.current.addEventListener('mouseover', handleMouseOver)
I did a little recoding, I think I did everything right

2023-02-22 16:00 UTC, dipSyxx commented on src/pages/index.tsx
> +              {productsCards}
less code :)

2023-02-22 16:20 UTC, dipSyxx commented on src/features/ProductCardMain/index.tsx
> +import { ProductCardMainInfoProps } from '@data/ProductCardInfo'
i  got you)

2023-02-22 19:16 UTC, dipSyxx commented on src/pages/index.tsx
> +              {productsCards}
fixed :)

2023-03-07 08:09 UTC, MaksPapirovnyk approved these changes

2023-03-07 08:09 UTC, merged