feat:[RP-21] - Button with variants
frontend-education-projects/rozetka pull request #6
Opened 2023-01-05 21:52 UTC by dipSyxx

# Title
Button with variants

## Ticket Link
https://rozetka-home-project.atlassian.net/browse/RP-21

## Changes
-Added demo variants
-Added to the button href,type, disabled, onClick
-Added some styles to the global styles for the button
## Info
-Custom button with clear understanding wich variants we have
## Screenshots
FINAL RESULT:

![Screenshot_1](https://user-images.githubusercontent.com/113060461/212097528-ef405b81-3d7b-470b-bb5f-2a31a2f2a641.png)

2023-01-10 09:32 UTC, MaksPapirovnyk commented
Screenshots of UI, to understand the final result

2023-01-10 09:35 UTC, MaksPapirovnyk commented on src/elements/Button/Button.tsx
> +  component: ElementType
`component: ElementType` so the button can be any HTML element or maybe `<a>`(if we have a link) and `<button>`

2023-01-10 09:50 UTC, MaksPapirovnyk commented on src/elements/Button/Button.tsx
> +  variant?: 'green' | 'linkButton' | 'outlined'
`variant?: 'green' | 'linkButton' | 'outlined'`
separate buttons by usage, for example, the most popular is `primary`,  then maybe `secondary`
if you want to have a link, just use the `href` props and if passed a link so you can automatically pick up the `href` variant

2023-01-10 09:50 UTC, MaksPapirovnyk commented on src/elements/Button/Button.tsx
> +  disabled?: 'isValid' | boolean
`disabled?: boolean`

2023-01-10 09:51 UTC, MaksPapirovnyk commented on src/elements/Button/Button.tsx
> +  type?: 'submit'
` type?: 'submit'` lets leave `type="button"` hardcoded and remove this props

2023-01-10 09:55 UTC, MaksPapirovnyk commented on src/elements/AuthModalSocials/AuthModalSocials.tsx
> +          <i className="fa-brands fa-facebook-f" /> Facebook
looks like you made changes for another ticket, don't touch parts of a code if it's already in another merge request or in progress, you may cause conflicts

2023-01-10 09:56 UTC, MaksPapirovnyk commented on src/styles/globalButtonsStyle.sass
> +a
the same about global styles and modifying code of anther PR

2023-01-11 21:51 UTC, MaksPapirovnyk commented on src/elements/Button/Button.tsx
> +  variant?: 'primary' | 'secondary' | 'tertiary' | 'href' | 'href_'
`| 'href' | 'href_'` why? :) what does it mean?

2023-01-11 21:52 UTC, MaksPapirovnyk commented on src/elements/Button/Button.tsx
> +  component: ElementType
Why you resolved this?

2023-01-11 21:54 UTC, MaksPapirovnyk commented on src/elements/Button/Button.tsx
> +  classVariant: string
`classVariant ` what does it mean? is it a specific variant classname? or it's just a custom classname for the button?

2023-01-11 21:59 UTC, MaksPapirovnyk commented on src/elements/Button/Button.module.sass
> +//!variant
looks very messy, with a lot of `important` fragile styles. 
this needs refactoring, add TODO about this.

2023-01-11 22:02 UTC, MaksPapirovnyk requested changes
IN THE DESCRIPRICTION OF THE TICKET USE SCEREENSHOTS OF FINAL IMPLEMENTATION OF THE UI, FOR EXAMPLE SHOW THE VARIANTS OF CREATED BUTTONS! NOT CODE! NOT CODE! NOT CODE! THE CODE IN THE PR :)

2023-01-11 22:03 UTC, MaksPapirovnyk commented
We don't need button for all occasions, we need button with clear understanding wich variants we have

2023-01-11 22:04 UTC, MaksPapirovnyk commented
Please resolve conflicts

2023-01-12 12:15 UTC, dipSyxx commented on src/elements/Button/Button.tsx
> +  variant?: 'primary' | 'secondary' | 'tertiary' | 'href' | 'href_'
it mean link with text-decoration: underline :)

2023-01-12 13:00 UTC, dipSyxx commented on src/elements/Button/Button.tsx
> +  variant?: 'primary' | 'secondary' | 'tertiary' | 'href' | 'href_'
i already fixed it :)

2023-01-12 13:03 UTC, dipSyxx commented on src/elements/Button/Button.tsx
> +  component: ElementType
fixed, now we can insert only element a (if we have link) and button

2023-01-18 11:24 UTC, MaksPapirovnyk approved these changes
LGTM

2023-01-18 11:24 UTC, merged